# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KugouApiWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from components.data_table_widgets.search_table_widgets import SearchTableWidget


class Ui_KugouApiWidget(object):
    def setupUi(self, KugouApiWidget):
        KugouApiWidget.setObjectName("KugouApiWidget")
        KugouApiWidget.resize(814, 525)
        KugouApiWidget.setMinimumSize(QtCore.QSize(814, 525))
        self.verticalLayout = QtWidgets.QVBoxLayout(KugouApiWidget)
        self.verticalLayout.setContentsMargins(0, 20, 0, 4)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_label = QtWidgets.QLabel(KugouApiWidget)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_3.addWidget(self.title_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_button = QtWidgets.QPushButton(KugouApiWidget)
        self.search_button.setMinimumSize(QtCore.QSize(35, 35))
        self.search_button.setMaximumSize(QtCore.QSize(35, 35))
        self.search_button.setText("")
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.search_lineEdit = QtWidgets.QLineEdit(KugouApiWidget)
        self.search_lineEdit.setMinimumSize(QtCore.QSize(241, 35))
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout_2.addWidget(self.search_lineEdit)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.undo_button = QtWidgets.QPushButton(KugouApiWidget)
        self.undo_button.setMinimumSize(QtCore.QSize(10, 10))
        self.undo_button.setMaximumSize(QtCore.QSize(35, 35))
        self.undo_button.setObjectName("undo_button")
        self.horizontalLayout.addWidget(self.undo_button)
        self.redo_button = QtWidgets.QPushButton(KugouApiWidget)
        self.redo_button.setMinimumSize(QtCore.QSize(10, 10))
        self.redo_button.setMaximumSize(QtCore.QSize(35, 35))
        self.redo_button.setObjectName("redo_button")
        self.horizontalLayout.addWidget(self.redo_button)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.search_path_label = QtWidgets.QLabel(KugouApiWidget)
        self.search_path_label.setObjectName("search_path_label")
        self.verticalLayout.addWidget(self.search_path_label)
        self.search_data_tablewidget = SearchTableWidget(KugouApiWidget)
        self.search_data_tablewidget.setMinimumSize(QtCore.QSize(0, 276))
        self.search_data_tablewidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.search_data_tablewidget.setObjectName("search_data_tablewidget")

        self.verticalLayout.addWidget(self.search_data_tablewidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.last_page_button = QtWidgets.QPushButton(KugouApiWidget)
        self.last_page_button.setMinimumSize(QtCore.QSize(35, 35))
        self.last_page_button.setText("")
        self.last_page_button.setObjectName("last_page_button")
        self.horizontalLayout_4.addWidget(self.last_page_button)
        self.page_label = QtWidgets.QLabel(KugouApiWidget)
        self.page_label.setObjectName("page_label")
        self.horizontalLayout_4.addWidget(self.page_label)
        self.next_page_button = QtWidgets.QPushButton(KugouApiWidget)
        self.next_page_button.setMinimumSize(QtCore.QSize(35, 35))
        self.next_page_button.setText("")
        self.next_page_button.setObjectName("next_page_button")
        self.horizontalLayout_4.addWidget(self.next_page_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(KugouApiWidget)
        QtCore.QMetaObject.connectSlotsByName(KugouApiWidget)

    def retranslateUi(self, KugouApiWidget):
        _translate = QtCore.QCoreApplication.translate
        KugouApiWidget.setWindowTitle(_translate("KugouApiWidget", "Form"))
        self.title_label.setText(_translate("KugouApiWidget", "  酷狗歌词api "))
        self.undo_button.setText(_translate("KugouApiWidget", "undo"))
        self.redo_button.setText(_translate("KugouApiWidget", "redo"))
        self.search_path_label.setText(_translate("KugouApiWidget", "path"))
        self.page_label.setText(_translate("KugouApiWidget", "TextLabel"))
