# -*- coding: utf-8 -*-

# Form implementation generated from reading ui1 file 'LyricsWindow.ui1'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import PyQt5

from components.lyrics_window.text_scroll_area import TextScrollArea
import ui_source.ui_type.source


class Ui_LyricsWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(803, 141)
        Form.setMinimumSize(QtCore.QSize(552, 106))
        Form.setMaximumSize(QtCore.QSize(1920, 308))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPixelSize(52)
        Form.setFont(font)
        Form.setStyleSheet("*\n"
                           "{\n"
                           "border:none;\n"
                           "}")
        Form.setWindowFlags(Qt.FramelessWindowHint |
                            QtCore.Qt.WindowStaysOnTopHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.gridLayout_10 = QtWidgets.QGridLayout(Form)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.background_frame = QtWidgets.QFrame(Form)
        self.background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.background_frame)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.buttons_frame = QtWidgets.QFrame(self.background_frame)
        self.buttons_frame.setMinimumSize(QtCore.QSize(552, 30))
        self.buttons_frame.setMaximumSize(QtCore.QSize(1920, 30))
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.main_frame = QtWidgets.QFrame(self.buttons_frame)
        self.main_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.main_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.main_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_button = QtWidgets.QPushButton(self.main_frame)
        self.main_button.setMinimumSize(QtCore.QSize(20, 20))
        self.main_button.setMaximumSize(QtCore.QSize(20, 20))
        self.main_button.setFont(font)
        self.main_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.main_button.setObjectName("main_button")
        self.gridLayout.addWidget(self.main_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.main_frame)
        self.last_frame = QtWidgets.QFrame(self.buttons_frame)
        self.last_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.last_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.last_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.last_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.last_frame.setObjectName("last_frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.last_frame)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.last_button = QtWidgets.QPushButton(self.last_frame)
        self.last_button.setMinimumSize(QtCore.QSize(20, 20))
        self.last_button.setMaximumSize(QtCore.QSize(20, 20))
        self.last_button.setFont(font)
        self.last_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.last_button.setStyleSheet("QPushButton \n"
                                       "{\n"
                                       "    border-image: url(:/pic/images/last.png);\n"
                                       "}")
        self.last_button.setText("")
        self.last_button.setObjectName("last_button")
        self.gridLayout_9.addWidget(self.last_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.last_frame)
        self.pause_frame = QtWidgets.QFrame(self.buttons_frame)
        self.pause_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.pause_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.pause_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pause_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pause_frame.setObjectName("pause_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pause_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pause_button = QtWidgets.QPushButton(self.pause_frame)
        self.pause_button.setMinimumSize(QtCore.QSize(20, 20))
        self.pause_button.setMaximumSize(QtCore.QSize(20, 20))
        self.pause_button.setFont(font)
        self.pause_button.setCursor(
            QtGui.QCursor(
                QtCore.Qt.PointingHandCursor))
        self.pause_button.setStyleSheet(
            "QPushButton \n"
            "{\n"
            "    border-image: url(:/pic/images/continue.png);\n"
            "}")
        self.pause_button.setText("")
        self.pause_button.setObjectName("pause_button")
        self.gridLayout_2.addWidget(self.pause_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.pause_frame)
        self.next_frame = QtWidgets.QFrame(self.buttons_frame)
        self.next_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.next_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.next_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.next_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.next_frame.setObjectName("next_frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.next_frame)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.next_button = QtWidgets.QPushButton(self.next_frame)
        self.next_button.setMinimumSize(QtCore.QSize(20, 20))
        self.next_button.setMaximumSize(QtCore.QSize(20, 20))
        self.next_button.setFont(font)
        self.next_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button.setStyleSheet("QPushButton \n"
                                       "{\n"
                                       "    border-image: url(:/pic/images/next.png);\n"
                                       "}")
        self.next_button.setText("")
        self.next_button.setObjectName("next_button")
        self.gridLayout_8.addWidget(self.next_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.next_frame)
        self.setting_frame = QtWidgets.QFrame(self.buttons_frame)
        self.setting_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.setting_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.setting_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame.setObjectName("setting_frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.setting_frame)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.settings_button = QtWidgets.QPushButton(self.setting_frame)
        self.settings_button.setMinimumSize(QtCore.QSize(20, 20))
        self.settings_button.setMaximumSize(QtCore.QSize(20, 20))
        self.settings_button.setFont(font)
        self.settings_button.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_button.setStyleSheet(
            "QPushButton \n" "{\n" "    border-image: url(:/pic/images/settings.png);\n" "}")
        self.settings_button.setText("")
        self.settings_button.setObjectName("settings_button")
        self.gridLayout_7.addWidget(self.settings_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.setting_frame)
        self.lock_frame = QtWidgets.QFrame(self.buttons_frame)
        self.lock_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.lock_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.lock_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lock_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lock_frame.setObjectName("lock_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.lock_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lock_button = QtWidgets.QPushButton(self.lock_frame)
        self.lock_button.setMinimumSize(QtCore.QSize(20, 20))
        self.lock_button.setMaximumSize(QtCore.QSize(20, 20))
        self.lock_button.setFont(font)
        self.lock_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lock_button.setObjectName("lock_button")
        self.gridLayout_3.addWidget(self.lock_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.lock_frame)
        self.offsetDown_frame = QtWidgets.QFrame(self.buttons_frame)
        self.offsetDown_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.offsetDown_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.offsetDown_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.offsetDown_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.offsetDown_frame.setObjectName("offsetDown_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.offsetDown_frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.offsetDown_button = QtWidgets.QPushButton(self.offsetDown_frame)
        self.offsetDown_button.setMinimumSize(QtCore.QSize(20, 20))
        self.offsetDown_button.setMaximumSize(QtCore.QSize(20, 20))
        self.offsetDown_button.setFont(font)
        self.offsetDown_button.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.offsetDown_button.setObjectName("offsetDown_button")
        self.gridLayout_6.addWidget(self.offsetDown_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.offsetDown_frame)
        self.offsetUp_frame = QtWidgets.QFrame(self.buttons_frame)
        self.offsetUp_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.offsetUp_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.offsetUp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.offsetUp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.offsetUp_frame.setObjectName("offsetUp_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.offsetUp_frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.offsetUp_button = QtWidgets.QPushButton(self.offsetUp_frame)
        self.offsetUp_button.setMinimumSize(QtCore.QSize(20, 20))
        self.offsetUp_button.setMaximumSize(QtCore.QSize(20, 20))
        self.offsetUp_button.setFont(font)
        self.offsetUp_button.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.offsetUp_button.setObjectName("offsetUp_button")
        self.gridLayout_5.addWidget(self.offsetUp_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.offsetUp_frame)
        self.close_frame = QtWidgets.QFrame(self.buttons_frame)
        self.close_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.close_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.close_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.close_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.close_frame.setObjectName("close_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.close_frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.close_button = QtWidgets.QPushButton(self.close_frame)
        self.close_button.setMinimumSize(QtCore.QSize(20, 20))
        self.close_button.setMaximumSize(QtCore.QSize(20, 20))
        self.close_button.setFont(font)
        self.close_button.setCursor(
            QtGui.QCursor(
                QtCore.Qt.PointingHandCursor))
        self.close_button.setStyleSheet(
            "QPushButton {\n" "    border-image: url(:/pic/images/close.png);\n" "}\n" "")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.gridLayout_4.addWidget(self.close_button, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.close_frame)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_11.addWidget(self.buttons_frame, 0, 0, 1, 1)

        self.text1_scrollarea = TextScrollArea(self.background_frame)
        self.gridLayout_11.addWidget(self.text1_scrollarea, 1, 0, 1, 1)

        self.text2_scrollarea = TextScrollArea(self.background_frame)
        self.gridLayout_11.addWidget(self.text2_scrollarea, 2, 0, 1, 1)

        self.gridLayout_10.addWidget(self.background_frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_button.setToolTip(_translate("Form", "进入音乐详细页"))
        self.main_button.setText(_translate("Form", "1"))
        self.last_button.setToolTip(_translate("Form", "上一首"))
        self.pause_button.setToolTip(_translate("Form", "播放/暂停"))
        self.next_button.setToolTip(_translate("Form", "下一首"))
        self.settings_button.setToolTip(_translate("Form", "设置"))
        self.lock_button.setToolTip(_translate("Form", "锁定桌面歌词"))
        self.lock_button.setText(_translate("Form", "6"))
        self.offsetDown_button.setToolTip(_translate("Form", "歌词后退0.5s"))
        self.offsetDown_button.setText(_translate("Form", "7"))
        self.offsetUp_button.setToolTip(_translate("Form", "歌词前进0.5s"))
        self.offsetUp_button.setText(_translate("Form", "8"))
        self.close_button.setToolTip(_translate("Form", "关闭桌面歌词"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    MainUi = Ui_LyricsWindow()
    MainUi.setupUi(form)
    form.show()
    sys.exit(app.exec_())
