# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewPlaylistDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleInputDialog(object):
    def setupUi(self, SingleInputDialog):
        SingleInputDialog.setObjectName("NewPlaylistDialog")
        SingleInputDialog.resize(310, 157)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        SingleInputDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(SingleInputDialog)
        self.verticalLayout.setContentsMargins(-1, 16, -1, 17)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SingleInputDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(SingleInputDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(SingleInputDialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.buttonBox.setFont(font)
        self.buttonBox.setWhatsThis("")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SingleInputDialog)
        QtCore.QMetaObject.connectSlotsByName(SingleInputDialog)

    def retranslateUi(self, NewPlaylistDialog):
        _translate = QtCore.QCoreApplication.translate
        NewPlaylistDialog.setWindowTitle(_translate("NewPlaylistDialog", "Dialog"))
        self.label.setText(_translate("NewPlaylistDialog", " "))
